# Generated by Django 5.0.4 on 2024-05-27 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='employee id')),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('employee_name', models.CharField(max_length=75, null=True, verbose_name='Employee Name')),
                ('employee_dept', models.CharField(max_length=50, null=True, verbose_name='Employee Department')),
                ('employee_dob', models.DateField(null=True, verbose_name='Employee Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
