# Generated by Django 5.0.4 on 2024-05-28 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.IntegerField(unique=True, verbose_name='employee id'),
        ),
        migrations.CreateModel(
            name='CheckinLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField(default=datetime.time(13, 24, 40, 666084), verbose_name='Employee Checkin Time')),
                ('checkout_time', models.TimeField(default=None, null=True, verbose_name='Employee Checkout Time')),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.employeeprofile')),
            ],
        ),
    ]
