# Generated by Django 5.0.4 on 2024-05-28 17:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_employeeprofile_employee_id_checkinlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlogs',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(22, 30, 23, 498592), verbose_name='Employee Checkin Time'),
        ),
        migrations.CreateModel(
            name='CheckinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.employeeprofile')),
            ],
        ),
    ]
