# Generated by Django 5.0.4 on 2024-05-28 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_checkinlogs_checkin_time_checkinstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinstatus',
            name='checkin_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkinlogs',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(22, 47, 23, 777459), verbose_name='Employee Checkin Time'),
        ),
    ]
