# Generated by Django 5.0.4 on 2024-05-28 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_checkinstatus_checkin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlogs',
            name='checkin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='checkinlogs',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(23, 45, 53, 572766), verbose_name='Employee Checkin Time'),
        ),
    ]
