# Generated by Django 5.0.4 on 2024-05-28 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_checkinlogs_checkin_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlogs',
            name='checkout_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='checkinlogs',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(23, 53, 9, 528476), verbose_name='Employee Checkin Time'),
        ),
    ]
